#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo Stopping existing
$DIR/stop
echo Building
$DIR/build
docker run -d --restart=always -p 127.0.0.1:4141:4141 trop-runner

echo Runner is now, well, running...